CREATE TABLE BRAND(ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(32) NOT NULL,
PRIMARY KEY ( ID ));

CREATE TABLE PRICE(ID INT NOT NULL AUTO_INCREMENT,
BRAND_ID INT,
PRICE_START_DATE TIMESTAMP NOT NULL,
PRICE_END_DATE TIMESTAMP NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRICE_PRIORITY INT NOT NULL,
PRICE NUMERIC(20,3) NOT NULL,
CURRENCY VARCHAR(32) NOT NULL,
PRIMARY KEY ( ID ));

ALTER TABLE PRICE
    ADD FOREIGN KEY (BRAND_ID)
    REFERENCES BRAND(ID);