CREATE TABLE BRAND(ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(32) NOT NULL,
PRIMARY KEY ( ID ));

CREATE TABLE PRICE(ID INT NOT NULL AUTO_INCREMENT,
BRAND_ID INT,
PRICE_START_DATE DATE NOT NULL,
PRICE_END_DATE DATE NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRICE_PRIORITY INT NOT NULL,
CURRENCY VARCHAR(32) NOT NULL,
PRIMARY KEY ( ID ));